# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0005_servicio_oficio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('o', 'Oficio'), ('c', 'Correo electr\xf3nico'), ('t', 'Tel\xe9fono')], max_length=1)),
                ('referencia', models.CharField(max_length=200)),
                ('interesado', models.CharField(max_length=200)),
                ('fechaSolicitud', models.DateField()),
                ('fechaRecibe', models.DateField(auto_now_add=True)),
                ('usuarioRecibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sol_recibe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
