# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='solicitud',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_solicitud', to='servicios.Solicitud'),
            preserve_default=False,
        ),
    ]
